### ISSUE TITLE
Move preprocessing modules to nf-core/modules

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#109]
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/scdownstream/issues/110
- [ ] https://github.com/nf-core/scdownstream/issues/111
- [ ] https://github.com/nf-core/scdownstream/issues/112
- [ ] https://github.com/nf-core/scdownstream/issues/113
- [ ] https://github.com/nf-core/scdownstream/issues/114
- [ ] https://github.com/nf-core/scdownstream/issues/115
- [ ] https://github.com/nf-core/scdownstream/issues/116
- [ ] https://github.com/nf-core/scdownstream/issues/117
- [ ] https://github.com/nf-core/scdownstream/issues/118
```
