### ISSUE TITLE
Implement doublet detection methods

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#14]
### Description of feature

SOLO has already been implemented. The following have been implemented in YASCP and could easily be adopted:
```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/scdownstream/issues/15
- [ ] https://github.com/nf-core/scdownstream/issues/16
- [ ] https://github.com/nf-core/scdownstream/issues/17
- [ ] https://github.com/nf-core/scdownstream/issues/18
- [ ] https://github.com/nf-core/scdownstream/issues/19
``` 

Should probably discuss with the authors of YASCP first, which ones worked best for them

**Comment by grst** [comment]
doubletFinder came out best in [this benchmark](https://doi.org/10.1016/j.cels.2020.11.008) and also worked well for me anecdotically.
