### ISSUE TITLE
Implement methods for ambient RNA removal

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#25]
### Description of feature

decontX has already been implemented. The following methods also look interesting:

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/scdownstream/issues/26
- [ ] https://github.com/nf-core/scdownstream/issues/27
- [ ] https://github.com/nf-core/scdownstream/issues/31
```

**Comment by grst** [comment]
There's also [scAR](https://github.com/Novartis/scAR) which is a newer, autoencoder-based method. 

Here's a [benchmark paper](https://doi.org/10.1186/s13059-023-02978-x) that recommends cellbender, but also argues that most downstream tasks do not benefit from ambient RNA removal (except for manual cell-type annotation).
