### ISSUE TITLE
Implement pathway analysis

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#3]
### Description of feature

This should be done based on the generated clustering.

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/scdownstream/issues/4
- [ ] https://github.com/nf-core/scdownstream/issues/5
- [ ] https://github.com/nf-core/scdownstream/issues/6
```
