### ISSUE TITLE
Implement integration methods

### ISSUE THREAD

**Issue by nictru** [nf-core/scdownstream#7]
### Description of feature

The integration methods should be added to the existing [integration subworkflow](https://github.com/nf-core/scdownstream/blob/dev/subworkflows/local/integrate.nf). Example wrapper scripts for all integration methods listed here can be found in the [scib repo](https://github.com/theislab/scib).

The following methods should probably be investigated first:

```[tasklist]
### Tasks
- [ ] https://github.com/nf-core/scdownstream/issues/8
- [ ] https://github.com/nf-core/scdownstream/issues/9
- [ ] https://github.com/nf-core/scdownstream/issues/10
- [ ] https://github.com/nf-core/scdownstream/issues/11
- [ ] https://github.com/nf-core/scdownstream/issues/12
``` 

Others, that could be investigated later on:
```[tasklist]
### Tasks
- [ ] Implement Conos integration
- [ ] Implement DESC integration
- [ ] Implement FastMNN integration
- [ ] Implement SAUCIE integration
- [ ] Implement Scanorama integration
- [ ] Implement Trvae(p) integration
```

**Comment by grst** [comment]
I would add scVI/scANVI to the high-priority list

**Comment by nictru** [comment]
They are so high-priority that I already implemented them ;)
